In [77]:
# Generating a 3x3 Matrix using List Comprehension, and without the use of a package

array1 = [[['5' for col in range(6)] for col in range(4)] for row in range(3)]
array1

[[['5', '5', '5', '5', '5', '5'],
  ['5', '5', '5', '5', '5', '5'],
  ['5', '5', '5', '5', '5', '5'],
  ['5', '5', '5', '5', '5', '5']],
 [['5', '5', '5', '5', '5', '5'],
  ['5', '5', '5', '5', '5', '5'],
  ['5', '5', '5', '5', '5', '5'],
  ['5', '5', '5', '5', '5', '5']],
 [['5', '5', '5', '5', '5', '5'],
  ['5', '5', '5', '5', '5', '5'],
  ['5', '5', '5', '5', '5', '5'],
  ['5', '5', '5', '5', '5', '5']]]

In [1]:
import numpy as np

In [5]:
a = np.array(array1)
a

array([[['5', '5', '5', '5', '5', '5'],
        ['5', '5', '5', '5', '5', '5'],
        ['5', '5', '5', '5', '5', '5'],
        ['5', '5', '5', '5', '5', '5']],

       [['5', '5', '5', '5', '5', '5'],
        ['5', '5', '5', '5', '5', '5'],
        ['5', '5', '5', '5', '5', '5'],
        ['5', '5', '5', '5', '5', '5']],

       [['5', '5', '5', '5', '5', '5'],
        ['5', '5', '5', '5', '5', '5'],
        ['5', '5', '5', '5', '5', '5'],
        ['5', '5', '5', '5', '5', '5']]], dtype='<U1')

In [6]:
a.shape

(3, 4, 6)

In [5]:
arr_wopkg = [[5]*3]
print(arr_wopkg)

arr_p = np.array(arr_wopkg)
print(arr_p)
print(arr_p.shape)

[[5, 5, 5]]
[[5 5 5]]
(1, 3)


### Initializing Different Types of Arrays

In [71]:
# Matrix of all 0's
np.zeros(5, dtype=int)

array([0, 0, 0, 0, 0])

In [74]:
np.zeros((3,3), dtype='int32')

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [75]:
# Matrix of all 1's
np.ones((2,3,4), dtype=int)

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]])

In [76]:
# Matrix of different values
np.full((3,3), 69, dtype=int)

array([[69, 69, 69],
       [69, 69, 69],
       [69, 69, 69]])

##### Other Array Creation Routines

In [80]:
# Create an array
vv = np.array([[1,2,3,4,5,6,7], [8,9,10,11,12,13,14]]) #list of lists
print(vv)

# Use '.full_like' to copy the shape
vt = np.full_like(vv, 34)
print(vt)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]
[[34 34 34 34 34 34 34]
 [34 34 34 34 34 34 34]]


In [82]:
# Random decimal numbers
np.random.random((3,3))

array([[0.50310967, 0.27093734, 0.76929174],
       [0.04218309, 0.43545463, 0.55761146],
       [0.29580695, 0.0828172 , 0.22215867]])

In [87]:
# Random integer numbers
np.random.randint(2, 14, 4)

array([ 3,  4,  7, 13])

In [5]:
# More on randint
np.random.randint(-11, 9, size=(3,3))

array([[ -5,  -7, -10],
       [ -9,  -7,   6],
       [  3,   4,   5]])

In a subtle way numpy blurs the distinction between the list and the nested list. Here is a demonstration:

In [92]:
list1 = [0,1,2,3]
list2 = [[0,1,2,3]]
print(len(list1))  # >> 4 (a list of 4 elements)
print(len(list2)) # >> 1 (one single element, a list)
print(len(list2[0])) # >> 4 (from inside the list, we again have 4 elements)

4
1
4


In [95]:
# Converting these aforementioned lists into NumPy array
lla1 = np.array(list1)
lla2 = np.array(list2)

print(lla1.shape)  # >> (4,) : a tuple representing 4 element 1-dim vector
print(lla2.shape)  # >> (1,4) : '1' list of '4' elements

(4,)
(1, 4)


In [100]:
# array(list)[None,:] produces the (1,4) version
(np.array(list1)[None, :]).shape

(1, 4)

In [101]:
# array(list).ravel() produces a (4,) version.
(np.array(list1).ravel()).shape

(4,)

In [7]:
# Identity Matrix (of size 'n')
np.identity(5, dtype=int)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [14]:
# Repeating an Array
arr = np.array([1,2,3])
f1 = np.repeat(arr, 4)
print(f1)

arrr = np.array([[1,2,3]])
f2 = np.repeat(arrr, 4, axis=0)
print(f2)

[1 1 1 1 2 2 2 2 3 3 3 3]
[[1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]]


##### OUTPUT THIS

1 1 1 1 1

1 0 0 0 1

1 0 9 0 1

1 0 0 0 1

1 1 1 1 1

In [21]:
one_1 = np.ones((5,5))
z = np.zeros((3,3))
z[1,1] = 9
one_1[1:4, 1:4] = z     # OR 1:-1, 1:-1
print(one_1)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


## ARRAY ARITHMETIC

In [3]:
#Creating an array called 'data' : 
data = np.array([1,2])
print(data)

#Creating an array called 'ones' :
ones = np.ones(2, dtype=int)
print(ones)

[1 2]
[1 1]


In [8]:
#Simple Addition
print(data + ones)

[2 3]


In [19]:
#Not only addition, but we can perform other operations as well :
# a. Subtraction
print("Subtraction:")
print(data - ones)
print("\n")

# b. Multiplication
print("Multiplication:")
print(data * data)
print("\n")

# c. Division
print("Division:")
print(data / data)
print("\n")

# d. Exponentiation
print("Exponentiation:")
print(data ** ones)
print("\n")

# e. Modulo
print("Multiplication:")
print(data % data)
print("\n")

Subtraction:
[0 1]


Multiplication:
[1 4]


Division:
[1. 1.]


Exponentiation:
[1 2]


Multiplication:
[0 0]




#### Vector & Scalar

In [21]:
#Multiplication between a scalar and a vector
# Let's say our array 'data' represent distance in miles, and we want to convert it to kilometers

a = (data * 1.6)
print(a)
print(a.shape)

[1.6 3.2]
(2,)


In [39]:
def most_common_character(s):
    return max(s, key=s.count)

In [40]:
most_common_character('apple')

'p'

In [42]:
str_to_count = "success"  
lower_str = str_to_count.lower()  
lst = []
for i in range(ord('a'), ord('z') + 1):  
    char = chr(i)  
    lst.append([char,lower_str.count(char)])

max_freq = max(lst, key=lambda lst: lst[1])
print(lst)  
print(max_freq[0], max_freq[1]/len(lower_str))

[['a', 0], ['b', 0], ['c', 2], ['d', 0], ['e', 1], ['f', 0], ['g', 0], ['h', 0], ['i', 0], ['j', 0], ['k', 0], ['l', 0], ['m', 0], ['n', 0], ['o', 0], ['p', 0], ['q', 0], ['r', 0], ['s', 3], ['t', 0], ['u', 1], ['v', 0], ['w', 0], ['x', 0], ['y', 0], ['z', 0]]
s 0.42857142857142855


In [44]:
def find_max_frequency_char(phrase):
    # List of all possible characters in the phrase
    unique_chars = []

    # Collect unique characters from the phrase
    for char in phrase:
        if char not in unique_chars:
            unique_chars.append(char)

    # Initialize variables to keep track of the character with max frequency
    max_char = None
    max_count = 0

    # Iterate over each unique character to count its frequency in the phrase
    for char in unique_chars:
        count = phrase.count(char)
        if count > max_count:
            max_char = char
            max_count = count

    return max_char, max_count

# Example usage
phrase = "success"
max_char, frequency = find_max_frequency_char(phrase)
print(f"The character with the maximum frequency is: '{max_char}' with a frequency of {frequency}")

The character with the maximum frequency is: 's' with a frequency of 3


### Aggregation

Additional benefits NumPy gives us are aggregation functions: like .min(), .max(0), .sum(), et cetera.

In addition to min, max, and sum, you get all the greats like mean to get the average, prod to get the result of multiplying all the elements together, std to get standard deviation, and plenty of others.

In [5]:
data = np.array([1,2,3])
print(data)

print("Min()\n:", data.min())
print("Max()\n:", data.max())
print("Sum()\n:", data.sum())

[1 2 3]
Min()
 1
Max()
 3
Sum()
 6


### Creating Matricies

We can pass python lists of lists in the following shape to have NumPy create a matrix to represent them:

np.array([[1,2],[3,4]])

In [6]:
# Creating a matrice as list of lists

matrice = np.array([[1,2], [3,4]])
print(matrice)

[[1 2]
 [3 4]]


We can also use the same methods we mentioned above (ones(), zeros(), and random.random()) as long as we give them a tuple describing the dimensions of the matrix we are creating:

In [7]:
mat_one = np.ones((3,2))
print(mat_one, "\n")

mat_zero = np.zeros((3,2))
print(mat_zero, "\n")

mat_rand = np.random.random((3,2))
print(mat_rand, "\n")

[[1. 1.]
 [1. 1.]
 [1. 1.]]

[[0. 0.]
 [0. 0.]
 [0. 0.]]

[[0.55314151 0.97532509]
 [0.58855752 0.89469837]
 [0.2568368  0.44065279]]



### Matrix Arithmetic

We can add and multiply matrices using arithmetic operators (+-*/) if the two matrices are the same size. NumPy handles those as position-wise operations:

In [16]:
matone = np.ones((2,2), dtype=int)
print(matrice + matone)

[[2 3]
 [4 5]]


We can get away with doing these arithmetic operations on matrices of different size only if the different dimension is one (e.g. the matrix has only one column or one row), in which case NumPy uses its broadcast rules for that operation:    

In [17]:
ones_row = np.ones((1,2), dtype=int)
mat_3x3 = np.array([[1,2], [3,4], [5,6]])

print(mat_3x3 + ones_row)

[[2 3]
 [4 5]
 [6 7]]


### Dot Product

A key distinction to make with arithmetic is the case of matrix multiplication using the dot product. NumPy gives every matrix a dot() method we can use to carry-out dot product operations with other matrices:

In [19]:
data = np.array([1,2,3])
powers_of_ten = np.array([[1,10], [100,1000], [10000, 100000]], dtype=int)
print(powers_of_ten)

[[     1     10]
 [   100   1000]
 [ 10000 100000]]


In [21]:
dot_prod = data.dot(powers_of_ten)
print(dot_prod)

[ 30201 302010]


Remember that the two matrices have to have the same dimension on the side they face each other with:

1x3 : : 3x2  =  1x2

### Matrix Indexing

Indexing and slicing operations become even more useful when we’re manipulating matrices:

In [24]:
datum = np.array([[1,2], [3,4], [5,6]])
print(datum)

[[1 2]
 [3 4]
 [5 6]]


In [26]:
print(datum[0,1])

2


In [27]:
print(datum[1:3])

[[3 4]
 [5 6]]


In [28]:
print(datum[0:2,0])

[1 3]


### Matrix Aggregation

We can aggregate matrices the same way we aggregated vectors:

In [30]:
print(datum, "\n")

print("Min()\n", datum.min())
print("\n Max()\n", datum.max())
print("\n Sum()\n", datum.sum())

[[1 2]
 [3 4]
 [5 6]]

Min()
 1

 Max()
 6

 Sum()
 21


Not only can we aggregate all the values in a matrix, but we can also aggregate across the rows or columns by using the axis parameter:

In [31]:
dati = np.array([[1,2], [5,3], [4,6]])
print(dati)

[[1 2]
 [5 3]
 [4 6]]


In [32]:
# Finding the max down the columns, using axis=0

print(dati.max(axis=0))

[5 6]


In [35]:
# Finding the max across the rows, using axis=1

print(dati.max(axis=1))

[2 5 6]


### Transposing and Reshaping

A common need when dealing with matrices is the need to rotate them. This is often the case when we need to take the dot product of two matrices and need to align the dimension they share. NumPy arrays have a convenient property called T to get the transpose of a matrix:

In [36]:
print(datum)

[[1 2]
 [3 4]
 [5 6]]


In [37]:
# Transpose of our matrix

print(datum.T)

[[1 3 5]
 [2 4 6]]


In more advanced use case, you may find yourself needing to switch the dimensions of a certain matrix. This is often the case in machine learning applications where a certain model expects a certain shape for the inputs that is different from your dataset. NumPy’s reshape() method is useful in these cases. You just pass it the new dimensions you want for the matrix. You can pass -1 for a dimension and NumPy can infer the correct dimension based on your matrix:

In [38]:
lin_data = np.arange(1,7,1)
print(lin_data)

[1 2 3 4 5 6]


In [39]:
lin_data.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [40]:
lin_data.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [50]:
print(lin_data.reshape(-1, 3))

[[1 2 3]
 [4 5 6]]


### Yet More Dimensions

NumPy can do everything we’ve mentioned in any number of dimensions. Its central data structure is called ndarray (N-Dimensional Array) for a reason.

In [54]:
three_d = np.array([ [[1,2], [3,4]],
                     [[5,6], [7,8]] ])

print(three_d)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In a lot of ways, dealing with a new dimension is just adding a comma to the parameters of a NumPy function:

Note: Keep in mind that when you print a 3-dimensional NumPy array, the text output visualizes the array differently than just a stack of two matices. NumPy’s order for printing n-dimensional arrays is that the last axis is looped over the fastest, while the first is the slowest. Which means that np.ones((4,3,2)) would be printed as:

In [56]:
np.ones((4,3,2))

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [57]:
print(datum)

[[1 2]
 [3 4]
 [5 6]]


In [58]:
# Get a specific row
#     Get row 2

datum[1,:]

array([3, 4])

In [60]:
seven = np.array([[1,2,3,4,5,6,7], [8,9,10,11,12,13,14]]) #list of lists
print(seven)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [62]:
# Get every second element between 2 and 6 from matrix called 'seven'
#     A little fancy stuff - [startindex:endindex:stepsize]
seven[0, 1:6:2]

array([2, 4, 6])

In [63]:
# 3D Array Example
xb = np.array([[[1,2], [3,4]], [[5,6], [7,8]]])
print(xb)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [65]:
# Get a specific element : : : Pro-tip - (work outside in)
#     Get '4'
print(xb[0, 1, 1])

4


In [69]:
# Replace
#     Make sure the dimensions are same or it will throw an error
xb[:,1, :] = [[10, 11],
              [12, 13]]

In [70]:
xb

array([[[ 1,  2],
        [10, 11]],

       [[ 5,  6],
        [12, 13]]])

##### Be Extremely Cautious When Copying Arrays

In [22]:
# INSTEAD OF THIS :

test_arr_a = np.array([1,2,3,4])
copy_arr_b = test_arr_a
copy_arr_b[0] = 69
print(copy_arr_b)
print(test_arr_a)

[69  2  3  4]
[69  2  3  4]


In [23]:
# DO THIS :

test_a = np.array([1,2,3,4])
copy_b = test_a.copy()
copy_b[0] = 69
print(copy_b)
print(test_a)

[69  2  3  4]
[1 2 3 4]


### Mathematics

In [32]:
qw = np.array([1,2,3,4,5])
print(qw+2)

print(qw-1)

print(qw * 4)

print(qw / 0.5)

print(qw ** 3)

[3 4 5 6 7]
[0 1 2 3 4]
[ 4  8 12 16 20]
[ 2.  4.  6.  8. 10.]
[  1   8  27  64 125]


There are other Mathematical routines worth checking out!!!

### Linear Algebra

In [33]:
p = np.ones((2,3))
print(p)

q = np.full((3,2), 3)
print(q)

[[1. 1. 1.]
 [1. 1. 1.]]
[[3 3]
 [3 3]
 [3 3]]


Multiplying these two matrices by simply using a '*' while invite a Value error, stating "ValueError: operands could not be broadcast together with shapes (2,3) (3,2)". Instead do this:

In [36]:
np.matmul(p, q)

array([[9., 9.],
       [9., 9.]])

In [40]:
# Finding Determinant of a Matrix
'''Determinant of an identity matrix is 1.0'''

k = np.identity(4)
print(k)

print(np.linalg.det(k))

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
1.0


### Statistics

In [42]:
g = np.array([[1,2,3], [4,5,6]])
print(g)

[[1 2 3]
 [4 5 6]]


In [43]:
# Min of the array as a whole
np.min(g)

np.int32(1)

In [45]:
# Min of the array based on rows
np.min(g, axis=1)

array([1, 4])

In [46]:
# Min of the array based on columns
np.min(g, axis=0)

array([1, 2, 3])

In [47]:
# Max of the array as a whole
np.max(g)

np.int32(6)

In [48]:
# Max of the array based on rows
np.max(g, axis=1)

array([3, 6])

In [49]:
# Max of the array based on columns
np.max(g, axis=0)

array([4, 5, 6])

In [50]:
# Sum of the array
np.sum(g)

np.int32(21)

#### Reorganizing Arrays

In [51]:
# Reorganize the array
before = np.array([[1,2,3,4], [5,6,7,8]])
print(before)
print(before.shape)

[[1 2 3 4]
 [5 6 7 8]]
(2, 4)


In [52]:
after = before.reshape(8,1)
print(after)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]


In [53]:
later = before.reshape(1,8)
print(later)

[[1 2 3 4 5 6 7 8]]


In [54]:
fig = before.reshape(2,2,2)
print(fig)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [55]:
# Vertically Stacking of Arrays
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1, v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [66]:
# Horizontally Stacking of Arrays
h1 = np.ones((2,4), dtype=int)
h2 = np.zeros((2,2), dtype=int)

np.hstack([h2, h1], dtype=int)

array([[0, 0, 1, 1, 1, 1],
       [0, 0, 1, 1, 1, 1]])

### Miscellaneous

**Load Data from a file**

In [77]:
inpu = np.genfromtxt('dataa.txt', delimiter=',')
print(inpu)
inpu.astype('int32')
inpu = inpu.astype('int32')
print(inpu)

[[ 1.  2.  3.  4.  5.]
 [12. 13. 14. 16. 12.]
 [ 1.  2.  2.  2.  2.]]
[[ 1  2  3  4  5]
 [12 13 14 16 12]
 [ 1  2  2  2  2]]


#### Boolean Masking and Advanced Indexing

In [74]:
inpu > 11

array([[False, False, False, False, False],
       [ True,  True,  True,  True,  True],
       [False, False, False, False, False]])

In [78]:
inpu[inpu > 11]

array([12, 13, 14, 16, 12])

This aforementioned trick works in NumPy because you can index with a list in NumPy:

In [80]:
xer = np.array([1,2,3,4,5,6,7,8,9])

# Retrieve numbers 2, 4, 7, and 9

xer[[1,3,6,8]]

array([2, 4, 7, 9])

In [84]:
# To check if any value is greater than a certain number
np.any(inpu>12, axis=1)

array([False,  True, False])

In [87]:
# Multiple conditions
((inpu > 6) & (inpu < 14))

array([[False, False, False, False, False],
       [ True,  True, False, False,  True],
       [False, False, False, False, False]])

In [88]:
# Multiple conditions with negation
(~(inpu > 6) & (inpu < 14))

array([[ True,  True,  True,  True,  True],
       [False, False, False, False, False],
       [ True,  True,  True,  True,  True]])

In [89]:
test = np.array([[1,2,3,4,5],
                 [6,7,8,9,10],
                 [11,12,13,14,15],
                 [16,17,18,19,20],
                 [21,22,23,24,25],
                 [26,27,28,29,30]])

print(test)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]


Retrieve:

[ 11, 12 ]

[ 16, 17 ]

In [90]:
test[2:4, 0:2]

array([[11, 12],
       [16, 17]])

Retrieve:

* 2
* * 8
* * * 14
* * *  * 20

In [93]:
l1 = [0,1,2,3]
l2 = [1,2,3,4]
print(test[l1, l2])

"""OR"""

test[[0,1,2,3], [1,2,3,4]]

[ 2  8 14 20]


array([ 2,  8, 14, 20])

Retrieve: 

[ 4, 5 ]
.
.
.
.
.
.
.
.

[ 24, 25]

[29, 30]

In [119]:
test[[0,4,5], 3:]

array([[ 4,  5],
       [24, 25],
       [29, 30]])

### NumPy Documentation

Visit: https://numpy.org/doc/

### What NOW?

Now that we have covered the basics of Numpy, we can go ahead and immerse ourselves in the vast world that in computational and numerical programming. Practice. Read documentations. Read works of other enthusiasts and professionals on the topic!

***Hop On !***